### ISSUE TITLE
本地Windows和Ubuntu使用Cmake都报错，不知道作者放不方便提供以下二进制文件？

### ISSUE THREAD

**Issue by FWangZil** [hanhan-GKD/BigMoney#1]
* 试着解决了一下报错，奈何C/C艹能力不够没能成功解决问题。
* 作者老哥随意，有时间有心情看能不能麻烦提供一下，不提供也正常，毕竟开源项目没有这个必备义务。

* 提前感谢！

**Comment by FWangZil** [comment]
* 另附log文件 [CMakeOutput.log](https://github.com/hanhan-GKD/BigMoney/files/4936402/CMakeOutput.log)

**Comment by geniusC** [comment]
看日志文件， 应该是你工具链配置有问题。
已经上传release文件。

**Comment by FWangZil** [comment]
好的，多谢！
