### ISSUE TITLE
centos 7 编译错误

### ISSUE THREAD

**Issue by liusk98** [hanhan-GKD/BigMoney#2]
error code 
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.2.0 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
```
在按照readme中，cmake操作时出现的错误

**Comment by geniusC** [comment]
cmake版本过低

**Comment by six3git** [comment]
编译过程中，卡在了这一步骤：
`Cloning into '3rd/csylib'...
Submodule path '3rd/csylib': checked out 'e73a01a04796c1dbf397c702e348d736a2db5e61'
`

**Comment by geniusC** [comment]
> 编译过程中，卡在了这一步骤：
> `Cloning into '3rd/csylib'... Submodule path '3rd/csylib': checked out 'e73a01a04796c1dbf397c702e348d736a2db5e61' `

windows系统么？ 依赖于curl和rapidjson。 没有挂梯子，clone速度很慢。可以从gitee上clone对应的项目到3rd下面，然后执行cmake.

**Comment by six3git** [comment]
> > 编译过程中，卡在了这一步骤：
> > `Cloning into '3rd/csylib'... Submodule path '3rd/csylib': checked out 'e73a01a04796c1dbf397c702e348d736a2db5e61' `
> 
> windows系统么？ 依赖于curl和rapidjson。 没有挂梯子，clone速度很慢。可以从gitee上clone对应的项目到3rd下面，然后执行cmake.

CentOS Linux release 7.7.1908 (Core)
国内太慢了。

**Comment by geniusC** [comment]
> > > 编译过程中，卡在了这一步骤：
> > > `Cloning into '3rd/csylib'... Submodule path '3rd/csylib': checked out 'e73a01a04796c1dbf397c702e348d736a2db5e61' `
> > 
> > 
> > windows系统么？ 依赖于curl和rapidjson。 没有挂梯子，clone速度很慢。可以从gitee上clone对应的项目到3rd下面，然后执行cmake.
> 
> CentOS Linux release 7.7.1908 (Core)
> 国内太慢了。

linux系统只需要rapidjson，在码云上搜索rapidjson clone到3rd目录下就可以正常编译了。

**Comment by six3git** [comment]
> > > > 编译过程中，卡在了这一步骤：
> > > > `Cloning into '3rd/csylib'... Submodule path '3rd/csylib': checked out 'e73a01a04796c1dbf397c702e348d736a2db5e61' `
> > > 
> > > 
> > > windows系统么？ 依赖于curl和rapidjson。 没有挂梯子，clone速度很慢。可以从gitee上clone对应的项目到3rd下面，然后执行cmake.
> > 
> > 
> > CentOS Linux release 7.7.1908 (Core)
> > 国内太慢了。
> 
> linux系统只需要rapidjson，在码云上搜索rapidjson clone到3rd目录下就可以正常编译了。

操作步骤乱了，出问题了。
之前终止了这一步：Cloning into '3rd/csylib‘
然后执行了这一步：linux系统只需要rapidjson，在码云上搜索rapidjson clone到3rd目录下就可以正常编译了。
然后执行：cmake ../BigMoney
异常信息：
`-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetch submodule code into 3rd...
Clone of 'https://github.com/Tencent/rapidjson.git' into submodule path '3rd/rapidjson' failed
-- Build big_money on *nix system
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.18/Modules/FindCurses.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/build/CMakeFiles/CMakeOutput.log".
`

要上日志CMakeOutput.log么？没看出啥。

**Comment by geniusC** [comment]
yum install ncurses

**Comment by six3git** [comment]
rapidjson/rapidjson.h文件拷贝到哪里呢？

异常：
> [root@test build]# make -j16
Scanning dependencies of target big_money
[  9%] Building CXX object CMakeFiles/big_money.dir/src/colors.cc.o
[ 18%] Building CXX object CMakeFiles/big_money.dir/src/command_bar.cc.o
[ 27%] Building CXX object CMakeFiles/big_money.dir/src/earn.cc.o
[ 36%] Building CXX object CMakeFiles/big_money.dir/src/fund_board.cc.o
[ 45%] Building CXX object CMakeFiles/big_money.dir/src/help.cc.o
[ 54%] Building CXX object CMakeFiles/big_money.dir/src/main.cc.o
[ 63%] Building CXX object CMakeFiles/big_money.dir/src/msg.cc.o
[ 72%] Building CXX object CMakeFiles/big_money.dir/src/status_bar.cc.o
/root/BigMoney/src/fund_board.cc:2:33: fatal error: rapidjson/rapidjson.h: No such file or directory
 #include <rapidjson/rapidjson.h>
                                 ^
compilation terminated.
[ 81%] Building CXX object CMakeFiles/big_money.dir/src/timer.cc.o
[ 90%] Building CXX object CMakeFiles/big_money.dir/src/util.cc.o
make[2]: *** [CMakeFiles/big_money.dir/src/fund_board.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/big_money.dir/all] Error 2
make: *** [all] Error 2

文件：rapidjson/rapidjson.h
> [root@test 3rd]# find / -name rapidjson.h
/root/build/3rd/rapidjson/include/rapidjson/rapidjson.h

**Comment by geniusC** [comment]
> rapidjson/rapidjson.h文件拷贝到哪里呢？
> 
> 异常：
> 
> > [root@test build]# make -j16
> > Scanning dependencies of target big_money
> > [  9%] Building CXX object CMakeFiles/big_money.dir/src/colors.cc.o
> > [ 18%] Building CXX object CMakeFiles/big_money.dir/src/command_bar.cc.o
> > [ 27%] Building CXX object CMakeFiles/big_money.dir/src/earn.cc.o
> > [ 36%] Building CXX object CMakeFiles/big_money.dir/src/fund_board.cc.o
> > [ 45%] Building CXX object CMakeFiles/big_money.dir/src/help.cc.o
> > [ 54%] Building CXX object CMakeFiles/big_money.dir/src/main.cc.o
> > [ 63%] Building CXX object CMakeFiles/big_money.dir/src/msg.cc.o
> > [ 72%] Building CXX object CMakeFiles/big_money.dir/src/status_bar.cc.o
> > /root/BigMoney/src/fund_board.cc:2:33: fatal error: rapidjson/rapidjson.h: No such file or directory
> > #include <rapidjson/rapidjson.h>
> > ^
> > compilation terminated.
> > [ 81%] Building CXX object CMakeFiles/big_money.dir/src/timer.cc.o
> > [ 90%] Building CXX object CMakeFiles/big_money.dir/src/util.cc.o
> > make[2]: *** [CMakeFiles/big_money.dir/src/fund_board.cc.o] Error 1
> > make[2]: *** Waiting for unfinished jobs....
> > make[1]: *** [CMakeFiles/big_money.dir/all] Error 2
> > make: *** [all] Error 2
> 
> 文件：rapidjson/rapidjson.h
> 
> > [root@test 3rd]# find / -name rapidjson.h
> > /root/build/3rd/rapidjson/include/rapidjson/rapidjson.h

> cd BigMoney/3rd
> rm -rf rapidjson
> git clone https://gitee.com/mirrors/rapidjson.git

**Comment by six3git** [comment]
> > rapidjson/rapidjson.h文件拷贝到哪里呢？
> > 异常：
> > > [root@test build]# make -j16
> > > Scanning dependencies of target big_money
> > > [  9%] Building CXX object CMakeFiles/big_money.dir/src/colors.cc.o
> > > [ 18%] Building CXX object CMakeFiles/big_money.dir/src/command_bar.cc.o
> > > [ 27%] Building CXX object CMakeFiles/big_money.dir/src/earn.cc.o
> > > [ 36%] Building CXX object CMakeFiles/big_money.dir/src/fund_board.cc.o
> > > [ 45%] Building CXX object CMakeFiles/big_money.dir/src/help.cc.o
> > > [ 54%] Building CXX object CMakeFiles/big_money.dir/src/main.cc.o
> > > [ 63%] Building CXX object CMakeFiles/big_money.dir/src/msg.cc.o
> > > [ 72%] Building CXX object CMakeFiles/big_money.dir/src/status_bar.cc.o
> > > /root/BigMoney/src/fund_board.cc:2:33: fatal error: rapidjson/rapidjson.h: No such file or directory
> > > #include <rapidjson/rapidjson.h>
> > > ^
> > > compilation terminated.
> > > [ 81%] Building CXX object CMakeFiles/big_money.dir/src/timer.cc.o
> > > [ 90%] Building CXX object CMakeFiles/big_money.dir/src/util.cc.o
> > > make[2]: *** [CMakeFiles/big_money.dir/src/fund_board.cc.o] Error 1
> > > make[2]: *** Waiting for unfinished jobs....
> > > make[1]: *** [CMakeFiles/big_money.dir/all] Error 2
> > > make: *** [all] Error 2
> > 
> > 
> > 文件：rapidjson/rapidjson.h
> > > [root@test 3rd]# find / -name rapidjson.h
> > > /root/build/3rd/rapidjson/include/rapidjson/rapidjson.h
> 
> > cd BigMoney/3rd
> > rm -rf rapidjson
> > git clone https://gitee.com/mirrors/rapidjson.git

之前下的就是这个仓库
> 1026  git clone https://gitee.com/mirrors/rapidjson.git

**Comment by geniusC** [comment]
> > > rapidjson/rapidjson.h文件拷贝到哪里呢？
> > > 异常：
> > > > [root@test build]# make -j16
> > > > Scanning dependencies of target big_money
> > > > [  9%] Building CXX object CMakeFiles/big_money.dir/src/colors.cc.o
> > > > [ 18%] Building CXX object CMakeFiles/big_money.dir/src/command_bar.cc.o
> > > > [ 27%] Building CXX object CMakeFiles/big_money.dir/src/earn.cc.o
> > > > [ 36%] Building CXX object CMakeFiles/big_money.dir/src/fund_board.cc.o
> > > > [ 45%] Building CXX object CMakeFiles/big_money.dir/src/help.cc.o
> > > > [ 54%] Building CXX object CMakeFiles/big_money.dir/src/main.cc.o
> > > > [ 63%] Building CXX object CMakeFiles/big_money.dir/src/msg.cc.o
> > > > [ 72%] Building CXX object CMakeFiles/big_money.dir/src/status_bar.cc.o
> > > > /root/BigMoney/src/fund_board.cc:2:33: fatal error: rapidjson/rapidjson.h: No such file or directory
> > > > #include <rapidjson/rapidjson.h>
> > > > ^
> > > > compilation terminated.
> > > > [ 81%] Building CXX object CMakeFiles/big_money.dir/src/timer.cc.o
> > > > [ 90%] Building CXX object CMakeFiles/big_money.dir/src/util.cc.o
> > > > make[2]: *** [CMakeFiles/big_money.dir/src/fund_board.cc.o] Error 1
> > > > make[2]: *** Waiting for unfinished jobs....
> > > > make[1]: *** [CMakeFiles/big_money.dir/all] Error 2
> > > > make: *** [all] Error 2
> > > 
> > > 
> > > 文件：rapidjson/rapidjson.h
> > > > [root@test 3rd]# find / -name rapidjson.h
> > > > /root/build/3rd/rapidjson/include/rapidjson/rapidjson.h
> > 
> > 
> > > cd BigMoney/3rd
> > > rm -rf rapidjson
> > > git clone https://gitee.com/mirrors/rapidjson.git
> 
> 之前下的就是这个仓库
> 
> > 1026  git clone https://gitee.com/mirrors/rapidjson.git

克隆到源码目录， 不是build目录
